### ISSUE TITLE
Image Generation issue

### ISSUE THREAD

**Issue by opnoice** [dsdanielpark/Gemini-API#15]
Code Used:
```
from gemini import Gemini, GeminiImage

prompt = "Create illustrations of Seoul, South Korea."
response = GeminiClient.generate_content(prompt)

generated_images = response.generated_images # Check generated images [Dict]

GeminiImage.save_sync(generated_images, save_path="cached_folder")
```

Error:
```
Failed to download https://lh3.googleusercontent.com/bard/ADjfeTdRTWhsRmVFNH5LQJ7DRSghoivB2a50_FohrJQJtWe6CS4IMBWjjYcLFxgEUn6LtcC8dbM9wPOtxuJO92Ez_RhqcfZnH9k5EFwjL5YvCLy2PPC9jKy9PCDiONVJvAa47YD6K_XPWSjpK84_GoI1gHC6T4GUNj-FP3ezLqJjrofV1gUBFn7SBDLykYKrU7_o_xK0iaCs3Kb_UkpSpUqc5MRqaMQoMCf4EQm8gjVSFnfGGI43fcGs7CPb6_5ey4os203Hv8JA-SoyF1bYzF718H6Kq0D01dAq4KiC86aB1HzDcEpwWElOHBAxcQ9qAUHWWRpleUfq3ZZUOd4MS1o: Invalid type for url.  Expected str or httpx.URL, got <class 'pydantic_core._pydantic_core.Url'>: Url('https://lh3.googleusercontent.com/bard/ADjfeTdRTWhsRmVFNH5LQJ7DRSghoivB2a50_FohrJQJtWe6CS4IMBWjjYcLFxgEUn6LtcC8dbM9wPOtxuJO92Ez_RhqcfZnH9k5EFwjL5YvCLy2PPC9jKy9PCDiONVJvAa47YD6K_XPWSjpK84_GoI1gHC6T4GUNj-FP3ezLqJjrofV1gUBFn7SBDLykYKrU7_o_xK0iaCs3Kb_UkpSpUqc5MRqaMQoMCf4EQm8gjVSFnfGGI43fcGs7CPb6_5ey4os203Hv8JA-SoyF1bYzF718H6Kq0D01dAq4KiC86aB1HzDcEpwWElOHBAxcQ9qAUHWWRpleUfq3ZZUOd4MS1o')
Failed to download https://lh3.googleusercontent.com/bard/ADjfeTcTUw6txdmEd2o1EWED4rK5thrOeZO5xygpxYAy4fSkpd7qUuSBrtRafc5m9bYdbgoivXVKQEFWA7sXw3JHMnMi4BhM6q_dpEjiCIHxRloVLWJ7NRPTvmz_uf4gUrga3u0TSpo0OkIBlIdakvlj4WRy_dftihKOMwdarrrkrCM08rTPjnE5ASuvZC9RtD9xgaxpIGMfBAH1iXJRs6EHd9mQwiN03tlyHz_p0gXkV-H6y670lXCngR9h6ZCire0jJYsSLiU7HL0xu1_PLBDNylb7IDDzNWT1bN_ZVdx15jAb03jG5Plp38uJ3L8bEkAxDJVjV5E601d9eO-jD5Q: Invalid type for url.  Expected str or httpx.URL, got <class 'pydantic_core._pydantic_core.Url'>: Url('https://lh3.googleusercontent.com/bard/ADjfeTcTUw6txdmEd2o1EWED4rK5thrOeZO5xygpxYAy4fSkpd7qUuSBrtRafc5m9bYdbgoivXVKQEFWA7sXw3JHMnMi4BhM6q_dpEjiCIHxRloVLWJ7NRPTvmz_uf4gUrga3u0TSpo0OkIBlIdakvlj4WRy_dftihKOMwdarrrkrCM08rTPjnE5ASuvZC9RtD9xgaxpIGMfBAH1iXJRs6EHd9mQwiN03tlyHz_p0gXkV-H6y670lXCngR9h6ZCire0jJYsSLiU7HL0xu1_PLBDNylb7IDDzNWT1bN_ZVdx15jAb03jG5Plp38uJ3L8bEkAxDJVjV5E601d9eO-jD5Q')
Failed to download https://lh3.googleusercontent.com/bard/ADjfeTc1HGdWthxSjOuYeEUr5l3KPLTCuZyPrQEs9O0tD0eM-wZj_XDtjVX8i9-BqrW6EScAKpw29MMnaunZGANeLH1K16C2avYWUXDqY5zBQ3oqHVvWffUcN6YTZij3smFZ-58KzvC51E2t20Jayd9rYWcn6ZyZKV3cKEEQ2Lx1fV8zSyBIT5MMNdII6QofiV2hlvNKmC6QF5n8cC0ZejEvhDOLctw_IIosJWX3jh-bAPnNf8GmqEVoFBd6253ewoCUOlxDcaey9Iyn_q7CiXrj_f0rOx3kYVnPQGexZHnE3718Wa7Aum0l8EEcjZpsqcniOIEyFYIu2dw4zmsN2Do: Invalid type for url.  Expected str or httpx.URL, got <class 'pydantic_core._pydantic_core.Url'>: Url('https://lh3.googleusercontent.com/bard/ADjfeTc1HGdWthxSjOuYeEUr5l3KPLTCuZyPrQEs9O0tD0eM-wZj_XDtjVX8i9-BqrW6EScAKpw29MMnaunZGANeLH1K16C2avYWUXDqY5zBQ3oqHVvWffUcN6YTZij3smFZ-58KzvC51E2t20Jayd9rYWcn6ZyZKV3cKEEQ2Lx1fV8zSyBIT5MMNdII6QofiV2hlvNKmC6QF5n8cC0ZejEvhDOLctw_IIosJWX3jh-bAPnNf8GmqEVoFBd6253ewoCUOlxDcaey9Iyn_q7CiXrj_f0rOx3kYVnPQGexZHnE3718Wa7Aum0l8EEcjZpsqcniOIEyFYIu2dw4zmsN2Do')
Traceback (most recent call last):
  File "/home/container/app.py", line 37, in <module>
    GeminiImage.save_sync(generated_images, save_path="cached_folder")
  File "/home/container/.local/lib/python3.11/site-packages/gemini/src/model/image.py", line 116, in save_sync
    GeminiImage.validate_images(image_data)
  File "/home/container/.local/lib/python3.11/site-packages/gemini/src/model/image.py", line 20, in validate_images
    raise ValueError("Input is empty. Please provide images to proceed.")
ValueError: Input is empty. Please provide images to proceed.
```

**Comment by dsdanielpark** [comment]
This error means that Gemini did not generate a new image. 

Try explicitly changing the prompt to 'generate ~', and check the 'response.response_dict'. 

I'll modify the sample code and patch the version within 48 hours after completing the debugging.

**Comment by dsdanielpark** [comment]
I have checked this issue and try to resolve.

**Comment by dsdanielpark** [comment]
Try to pass `cookies` arguments, when you want to save generated images.

And if your error persist, please report again. I updated readme.

```python
from gemini import Gemini, GeminiImage

prompt = "Create illustrations of Seoul, South Korea."
response = GeminiClient.generate_content(prompt)

generated_images = response.generated_images # Check generated images [Dict]

GeminiImage.save_sync(generated_images, save_path="cached_folder", cookies = cookies)
```

**Comment by dsdanielpark** [comment]
[opnoice](https://github.com/opnoice)

Do you have still issue?
