### ISSUE TITLE
 Input should be a valid list [type=list_type, input_value='Gönderilen resimde "Saf...ihtimalini artırıyor.', input_type=str]

### ISSUE THREAD

**Issue by onlybicycle** [dsdanielpark/Gemini-API#21]
My gemini api version = 2.1.0

Traceback (most recent call last):
  File "C:\Users\Gumus\Desktop\gemini_api\main.py", line 7, in <module>
    response = GeminiClient.generate_content("Bu resmi bana açıklarmısın?", image=image_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gumus\AppData\Local\Programs\Python\Python312\Lib\site-packages\gemini\core.py", line 263, in generate_content
    return self._create_model_output(parsed_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gumus\AppData\Local\Programs\Python\Python312\Lib\site-packages\gemini\core.py", line 275, in _create_model_output
    candidates = self.collect_candidates(parsed_response)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gumus\AppData\Local\Programs\Python\Python312\Lib\site-packages\gemini\core.py", line 308, in collect_candidates
    collected.append(GeminiCandidate(**current))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gumus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GeminiCandidate
code
  Input should be a valid list [type=list_type, input_value='Gönderilen resimde "Saf...ihtimalini artırıyor.', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type

**Comment by OpenFXT** [comment]
@onlybicycle I also got the same error.

**Comment by dsdanielpark** [comment]
I will update with hot-fix ASAP. Thank you reporting.

**Comment by dsdanielpark** [comment]
[onlybicycle](https://github.com/onlybicycle), [OpenFXT](https://github.com/OpenFXT)

Try to using `2.2.0`. https://github.com/dsdanielpark/Gemini-API/releases/tag/2.2.0

If errors persist, using `2.1.0` or `2.0.0`

**Comment by dsdanielpark** [comment]
This issue has been resolved and merged. Closing due to inactivity. Please reopen if it recurs.
