### ISSUE TITLE
from const import FreeModel ModuleNotFoundError: No module named 'const'

### ISSUE THREAD

**Issue by wealthr** [dsdanielpark/Gemini-API#29]
Tried running the example code 

```python
from gemini import OpenRouter

api_key = "<your_api_key>"
gemma_client = OpenRouter(api_key=api_key, model="google/gemma-7b-it:free")

prompt = "Do you know UCA academy in Korea?"
response = gemma_client.create_chat_completion(prompt)
print(response)
```

and i got the error 
```
Traceback (most recent call last):
  File "C:\Users\alima\PycharmProjects\Vent_Linkedin_bot\Test.py", line 2, in <module>
    from gemini import OpenRouter
  File "C:\Users\alima\PycharmProjects\Vent_Linkedin_bot\venv\lib\site-packages\gemini\__init__.py", line 5, in <module>
    from .src.modules.openrouter.client import OpenRouter
  File "C:\Users\alima\PycharmProjects\Vent_Linkedin_bot\venv\lib\site-packages\gemini\src\modules\openrouter\__init__.py", line 1, in <module>
    from .client import OpenRouter
  File "C:\Users\alima\PycharmProjects\Vent_Linkedin_bot\venv\lib\site-packages\gemini\src\modules\openrouter\client.py", line 2, in <module>
    from const import FreeModel
ModuleNotFoundError: No module named 'const'
```

**Comment by dsdanielpark** [comment]
Please try to use 2.4.6

```
pip install python-gemini-api==2.4.6
```

**Comment by wealthr** [comment]
i get this error using the 2.4.6

```python

Traceback (most recent call last):
  File "C:\Users\alima\PycharmProjects\Vent_Linkedin_bot\Test.py", line 5, in <module>
    from gemini import OpenRouter
  File "C:\Users\alima\PycharmProjects\Vent_Linkedin_bot\venv\lib\site-packages\gemini\__init__.py", line 5, in <module>
    from .src.modules.openrouter.client import OpenRouter
  File "C:\Users\alima\PycharmProjects\Vent_Linkedin_bot\venv\lib\site-packages\gemini\src\modules\openrouter\__init__.py", line 2, in <module>
    from .async_client import AsyncOpenRouter
  File "C:\Users\alima\PycharmProjects\Vent_Linkedin_bot\venv\lib\site-packages\gemini\src\modules\openrouter\async_client.py", line 1, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

```

**Comment by dsdanielpark** [comment]
Thank you! I will add aiohttp as a dependency package.

For now, you can fix that error by manually installing it as follows:
```
pip install aiohttp
```
