### ISSUE TITLE
SNlM0e token value not found. Double-check cookies dict value or pass it as Gemini(cookies=Dict())

### ISSUE THREAD

**Issue by opnoice** [dsdanielpark/Gemini-API#3]
Traceback (most recent call last):
  File "c:\Users\Divyanshi\Desktop\New\app.py", line 22, in <module>
    GeminiClient = Gemini(cookies=cookies)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyanshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gemini\core.py", line 97, in __init__
    self.token = self._get_snim0e()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyanshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gemini\core.py", line 221, in _get_snim0e
    raise Exception(
Exception: SNlM0e token value not found. Double-check cookies dict value or pass it as Gemini(cookies=Dict())

**Comment by opnoice** [comment]
I have no cookie named SNlM0e on gemini website

**Comment by opnoice** [comment]
i tried multiple times, same error, also i put whole website cookies

**Comment by PushkarOP** [comment]
Same issue

**Comment by dsdanielpark** [comment]
Aware of the error, likely due to fast cookie refresh. 

Aim to update by March for smoother use by many users after February work. Thanks. Submit other issues to #4.
