### ISSUE TITLE
Notice: Reverse Engineering and Feature Testing Ongoing Until March 1, 2024

### ISSUE THREAD

**Issue by dsdanielpark** [dsdanielpark/Gemini-API#4]
Please compile the major issues here until then. We are aware of most errors during the development process, and we are continuously working to make the error messages clearer.

Currently, we are focusing on checking the logic for receiving a normal response through reverse engineering and for automatically updating the cookie values in real-time.

Additionally, you can contribute to the initial package development at any time through a pull request. Any type of contribution is appreciated, but we ask for a significant amount of development for your first pull request.

Thank you.

**Comment by PushkarOP** [comment]
Attempt 8: Failed to process request: HTTP error occurred: 400 Client Error: Bad Request for url: https://gemini.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate. Check the POST_ENDPOINT and network connectivity.
Traceback (most recent call last):
  File "c:\Users\Divyanshi\Desktop\New\app.py", line 45, in <module>
    response = GeminiClient.generate_content(prompt)
  File "C:\Users\Divyanshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gemini\core.py", line 374, in generate_content
    f"Reached maximum attempts without success. Last status code: {execute_response.get('status_code', 'N/A')}"
UnboundLocalError: cannot access local variable 'execute_response' where it is not associated with a value

**Comment by dsdanielpark** [comment]
Using 0.1.4 with sync session. GeminiClient is under development. I will fix this issue during weekend and plan to relese.

**Comment by ephemeral8997** [comment]
```py
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://gemini.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate?bl=boq_assistant-bard-web-server_20240227.13_p0&hl=en&_reqid=2416370&rt=c&f.sid=None
```
